language: go
go:
        - 1.9.x
        - 1.10.x
        - 1.11.x
        - master
script:
        - go test ./...
        - go test -race ./...
        - diff -u <(echo -n) <(gofmt -d -s .)
after_success:
        - ./scripts/coverage.sh
